# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 423e117e4559bceab3c267fa0ebdd7d304d5fb23f65d341a919306fd8980a1f66151117659a1164e7241fb325af2bd915eb660ab669051dda3a2decff88ea026

test:
  secret_key_base: 0cf1572108898b5f4ebb8ee73f7250905b215a916d9b75be0c3f36781ab1ee603ad664b201ee3343743460d164eea6cfaf5caa7afe49428e93a8d107501a7fd4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
